config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :home, only: :index

  devise_for :users, class_name: "User::Record", controllers: { registrations: 'users/registrations'  }

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  resources :quizzes do
    resources :questions
    resources :quiz_availabilities, only: %i[index create]
  end

  namespace :quiz_realizations do
    resources :search, only: :create
  end

  resources :quiz_availabilities, only: :show

  resources :quiz_availabilities, only: %i[index show] do
    resources :finish, only: :create, controller: "quiz_availabilities/finish"
    resources :quiz_realizations, only: :create
  end

  resources :quiz_realizations, only: :show

  resources :questions, only: :show do
    resources :quiz_realizations, only: [] do
      resources :quiz_realization_answers, only: :new, controller: "quiz_realization_answers/new"
      resources :quiz_realization_answers, only: :create, controller: "quiz_realization_answers/respond_question"
    end
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: %i[show]

  add_breadcrumb "Quizzes", "#"

  def index
    @quizzes = ::Quiz::Record.all
  end

  def show
    add_breadcrumb @quiz.description, quiz_path(@quiz)
  end

  private

  def set_quiz
    @quiz = ::Quiz::Record.find(params[:id])
  end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_quiz.html.erb
  <p>
    <h2> <%= quiz.description %> </h2>
  </p>

app/views/quizzes/index.html.erb
<%= stylesheet_link_tag "quiz_index" %>

<% if current_user.teacher? %>
  <%= link_to(quiz_path(Quiz::Record.find_by(description: "História").id), class: "item item-1") do %>
    <section class="icon-1">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="70"
        height="80"
        fill="currentColor"
        class="bi bi-book-half"
        viewBox="0 0 16 16">
        <path
          d="M8.5 2.687c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z" />
      </svg>
    </section>
    História
  <% end %>

  <a href="#" class="item item-2">
    <section class="icon-2">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="68"
        height="80"
        fill="currentColor"
        class="bi bi-calculator-fill"
        viewBox="0 0 16 16">
        <path
          d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm2 .5v2a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 .5-.5v-2a.5.5 0 0 0-.5-.5h-7a.5.5 0 0 0-.5.5zm0 4v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5zM4.5 9a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zM4 12.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5zM7.5 6a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zM7 9.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5zm.5 2.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zM10 6.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5zm.5 2.5a.5.5 0 0 0-.5.5v4a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-4a.5.5 0 0 0-.5-.5h-1z" />
      </svg>
    </section>
    Matemática
  </a>

  <%= link_to(quiz_path(Quiz::Record.find_by(description: "Ciências").id), class: "item item-3") do %>
    <section class="icon-3">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="70"
        height="80"
        fill="currentColor"
        class="bi bi-radioactive"
        viewBox="0 0 16 16">
        <path
          d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1ZM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8Z" />
        <path
          d="M9.653 5.496A2.986 2.986 0 0 0 8 5c-.61 0-1.179.183-1.653.496L4.694 2.992A5.972 5.972 0 0 1 8 2c1.222 0 2.358.365 3.306.992L9.653 5.496Zm1.342 2.324a2.986 2.986 0 0 1-.884 2.312 3.01 3.01 0 0 1-.769.552l1.342 2.683c.57-.286 1.09-.66 1.538-1.103a5.986 5.986 0 0 0 1.767-4.624l-2.994.18Zm-5.679 5.548 1.342-2.684A3 3 0 0 1 5.005 7.82l-2.994-.18a6 6 0 0 0 3.306 5.728ZM10 8a2 2 0 1 1-4 0 2 2 0 0 1 4 0Z" />
      </svg>
    </section>
    Ciências
  <% end %>

  <a href="#" class="item item-4">
    <section class="icon-4">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="70"
        height="80"
        fill="currentColor"
        class="bi bi-globe2"
        viewBox="0 0 16 16">
        <path
          d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm7.5-6.923c-.67.204-1.335.82-1.887 1.855-.143.268-.276.56-.395.872.705.157 1.472.257 2.282.287V1.077zM4.249 3.539c.142-.384.304-.744.481-1.078a6.7 6.7 0 0 1 .597-.933A7.01 7.01 0 0 0 3.051 3.05c.362.184.763.349 1.198.49zM3.509 7.5c.036-1.07.188-2.087.436-3.008a9.124 9.124 0 0 1-1.565-.667A6.964 6.964 0 0 0 1.018 7.5h2.49zm1.4-2.741a12.344 12.344 0 0 0-.4 2.741H7.5V5.091c-.91-.03-1.783-.145-2.591-.332zM8.5 5.09V7.5h2.99a12.342 12.342 0 0 0-.399-2.741c-.808.187-1.681.301-2.591.332zM4.51 8.5c.035.987.176 1.914.399 2.741A13.612 13.612 0 0 1 7.5 10.91V8.5H4.51zm3.99 0v2.409c.91.03 1.783.145 2.591.332.223-.827.364-1.754.4-2.741H8.5zm-3.282 3.696c.12.312.252.604.395.872.552 1.035 1.218 1.65 1.887 1.855V11.91c-.81.03-1.577.13-2.282.287zm.11 2.276a6.696 6.696 0 0 1-.598-.933 8.853 8.853 0 0 1-.481-1.079 8.38 8.38 0 0 0-1.198.49 7.01 7.01 0 0 0 2.276 1.522zm-1.383-2.964A13.36 13.36 0 0 1 3.508 8.5h-2.49a6.963 6.963 0 0 0 1.362 3.675c.47-.258.995-.482 1.565-.667zm6.728 2.964a7.009 7.009 0 0 0 2.275-1.521 8.376 8.376 0 0 0-1.197-.49 8.853 8.853 0 0 1-.481 1.078 6.688 6.688 0 0 1-.597.933zM8.5 11.909v3.014c.67-.204 1.335-.82 1.887-1.855.143-.268.276-.56.395-.872A12.63 12.63 0 0 0 8.5 11.91zm3.555-.401c.57.185 1.095.409 1.565.667A6.963 6.963 0 0 0 14.982 8.5h-2.49a13.36 13.36 0 0 1-.437 3.008zM14.982 7.5a6.963 6.963 0 0 0-1.362-3.675c-.47.258-.995.482-1.565.667.248.92.4 1.938.437 3.008h2.49zM11.27 2.461c.177.334.339.694.482 1.078a8.368 8.368 0 0 0 1.196-.49 7.01 7.01 0 0 0-2.275-1.52c.218.283.418.597.597.932zm-.488 1.343a7.765 7.765 0 0 0-.395-.872C9.835 1.897 9.17 1.282 8.5 1.077V4.09c.81-.03 1.577-.13 2.282-.287z" />
      </svg>
    </section>
    Geografia
  </a>

  <a href="#" class="item item-5">
    <section class="icon-5">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="70"
        height="80"
        fill="currentColor"
        class="bi bi-chat-left-text-fill"
        viewBox="0 0 16 16">
        <path
          d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4.414a1 1 0 0 0-.707.293L.854 15.146A.5.5 0 0 1 0 14.793V2zm3.5 1a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5z" />
      </svg>
    </section>
    Linguagens
  </a>

  <a href="#" class="item item-6">
    <section class="icon-6">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="70"
        height="80"
        fill="currentColor"
        class="bi bi-shuffle"
        viewBox="0 0 16 16">
        <path
          fill-rule="evenodd"
          d="M0 3.5A.5.5 0 0 1 .5 3H1c2.202 0 3.827 1.24 4.874 2.418.49.552.865 1.102 1.126 1.532.26-.43.636-.98 1.126-1.532C9.173 4.24 10.798 3 13 3v1c-1.798 0-3.173 1.01-4.126 2.082A9.624 9.624 0 0 0 7.556 8a9.624 9.624 0 0 0 1.317 1.918C9.828 10.99 11.204 12 13 12v1c-2.202 0-3.827-1.24-4.874-2.418A10.595 10.595 0 0 1 7 9.05c-.26.43-.636.98-1.126 1.532C4.827 11.76 3.202 13 1 13H.5a.5.5 0 0 1 0-1H1c1.798 0 3.173-1.01 4.126-2.082A9.624 9.624 0 0 0 6.444 8a9.624 9.624 0 0 0-1.317-1.918C4.172 5.01 2.796 4 1 4H.5a.5.5 0 0 1-.5-.5z" />
        <path
          d="M13 5.466V1.534a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384l-2.36 1.966a.25.25 0 0 1-.41-.192zm0 9v-3.932a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384l-2.36 1.966a.25.25 0 0 1-.41-.192z" />
      </svg>
    </section>
    Customizado
  </a>
<% elsif current_user.student? %>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
  <style>
    .container {
      display: flex;
    }
  </style>
  <div style="margin: 0 auto">
  <%= form_with url: quiz_realizations_search_index_path, method: :post do |f| %>

    <%= f.label :quiz_availability_id, "Iniciar quiz" %>
    <%= f.text_field :quiz_availability_id %>
    <%= f.submit "Procurar", disable_with: 'Procurando' %>
  <% end %>
  </div>
  </div>
<% end %>

app/views/quizzes/show.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
<div style="margin: 0 auto">
<%= render "quiz", quiz: @quiz %>

<div id="questions">
  <div class="row">
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <%= link_to "Disponibilizar quiz", quiz_quiz_availabilities_path(quiz_id: @quiz.id), data: { "turbo-method": :post } %> |

          <% if (quiz_availability = current_user.quiz_availabilities.unfinished.find_by(quiz: @quiz)) %>
            <%= link_to "Iniciar quiz", quiz_availability_quiz_realizations_path(quiz_availability_id: quiz_availability.id),
                        data: { "turbo-method": :post } %> |

            <%= link_to "Finalizar disponibilização", quiz_availability_finish_index_path(quiz_availability_id: quiz_availability.id),
              data: { "turbo-method": :post } %> |
          <% end %>

          <%= link_to "Visualizar quizzes", quiz_quiz_availabilities_path(quiz_id: @quiz.id) %> |

          <%= link_to "Voltar", quizzes_path %>
        </div>
      </div>
    </div>
  </div>
</div>

<br>
<h2>Questões</h2>

<div id="questions">
  <div class="row">
    <div class="col-sm-12">
      <% @quiz.questions.each do |question| %>
        <div class="card">
          <div class="card-body">
            <%= render "questions/question", question: %>
          </div>
        </div>
        <br>
      <% end %>
      </div>
  </div>
</div>
</div>