config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :home, only: :index

  devise_for :users, class_name: "User::Record", controllers: { registrations: 'users/registrations'  }

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  resources :quizzes do
    resources :questions
    resources :quiz_availabilities, only: %i[index create]
  end

  namespace :quiz_realizations do
    resources :search, only: :create
  end

  resources :quiz_availabilities, only: :show

  resources :quiz_availabilities, only: %i[index show] do
    resources :finish, only: :create, controller: "quiz_availabilities/finish"
    resources :quiz_realizations, only: :create
  end

  resources :quiz_realizations, only: :show

  resources :questions, only: :show do
    resources :quiz_realizations, only: [] do
      resources :quiz_realization_answers, only: :new, controller: "quiz_realization_answers/new"
      resources :quiz_realization_answers, only: :create, controller: "quiz_realization_answers/respond_question"
    end
  end
end

app/controllers/quiz_availabilities/finish_controller.rb
module QuizAvailabilities
  class FinishController < ApplicationController
    before_action :set_quiz_availability, only: :create

    def create
      @quiz_availability.update!(finished_at: Time.zone.now)

      redirect_to quiz_path(
        id: @quiz_availability.quiz_id,
      ), notice: "Avaliação finalizada com sucesso."
    end

    private

    def set_quiz_availability
      @quiz_availability = current_user.quiz_availabilities.find(params[:quiz_availability_id])
    end
  end
end

app/controllers/quiz_availabilities_controller.rb
class QuizAvailabilitiesController < ApplicationController
  before_action :set_quiz, only: %i[index create]
  before_action :set_quiz_availability, only: %i[show]

  add_breadcrumb "Quizzes", "#"

  def index
    add_breadcrumb @quiz.description, quiz_path(@quiz)
    add_breadcrumb "Disponibilizados", "#"

    @quiz_availabilities = current_user.quiz_availabilities.where(quiz: @quiz)
  end

  def show
    add_breadcrumb @quiz_availability.quiz.description, quiz_path(@quiz_availability.quiz)
    add_breadcrumb "Disponibilizados", "#"
    add_breadcrumb "Exibir", "#"

    @scores = @quiz_availability.quiz_realizations.map(&:score)
    @boa_nota = @scores.select { |score| score >= 7 }
    @nota_na_media = @scores.select { |score| score >= 6 && score <= 7 }
    @nota_ruim = @scores.select { |score| score < 6 }

    @percentual_boa_nota = if @boa_nota.count.zero?
        0
      else
        (100 * @boa_nota.count) / @scores.count
      end

    @percentual_nota_na_media = if @nota_na_media.count.zero?
        0
      else
        (100 * @nota_na_media.count) / @scores.count
      end

    @percentual_nota_ruim = if @nota_ruim.count.zero?
        0
      else
        (100 * @nota_ruim.count) / @scores.count
      end
  end

  def create
    @quiz_availability = current_user.quiz_availabilities.create!(quiz: @quiz)

    redirect_to quiz_url(@quiz), notice: "Quiz iniciado com sucesso. Código: #{@quiz_availability.id}"
  end

  def set_quiz
    @quiz = ::Quiz::Record.find(params[:quiz_id])
  end

  def set_quiz_availability
    @quiz_availability = ::Quiz::Availability::Record.find(params[:id])
  end
end

app/views/quiz_availabilities/index.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />

<br>
<br>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Data de disponibilição</th>
      <th scope="col">Data de finalização</th>
      <th scope="col">Total realizado</th>
      <th scope="col">Nota média</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
      <% @quiz_availabilities.each.with_index do |quiz_availability, index| %>
    <tr>
        <th scope="row"><%= index %></th>
        <td><%= l(quiz_availability.created_at, format: :long) %></td>
        <td><%= l(quiz_availability.finished_at, format: :long) if quiz_availability.finished_at.present? %></td>
        <td><%= quiz_availability.quiz_realizations.finished.count %></td>
        <td><%= quiz_availability.average_score %></td>
        <td><%= link_to "Visualizar", quiz_availability_path(quiz_availability) %></td>
    </tr>
      <% end %>
  </tbody>
</table>

app/views/quiz_availabilities/show.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
<br>
<div style="margin: 0 auto;">
  <h1>Quiz Disponibilizado</h1>
  <div class="row">
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          Data de disponibilização: <%= l(@quiz_availability.created_at, format: :long) %><br>
          Data de finalização: <%= l(@quiz_availability.finished_at, format: :long) if @quiz_availability.finished_at.present? %><br>
          Total realizado <%= @quiz_availability.quiz_realizations.finished.count %><br>
          Nota média: <%= @quiz_availability.average_score %><br>
        </div>
      </div>
    </div>
  </div>

  <br>

  <h2>Realizados</h2>

  <div class="row">
    <% @quiz_availability.quiz_realizations.each do |quiz_realization| %>
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
              Email do participante: <%= quiz_realization.user.email %><br>
              Iniciado em: <%= l(quiz_realization.created_at, format: :long) %><br>
              Data de finalização: <%= l(quiz_realization.finished_at, format: :long) if quiz_realization.finished_at.present? %><br>
              Nota: <%= quiz_realization.score %><br><br>
          </div>
        </div>
        <br>
        <br>
      </div>
    <% end %>

    <script>
    window.onload = function() {

    const percentual_boa_nota = parseFloat("<%= @percentual_boa_nota %>")
    const percentual_nota_na_media = parseFloat("<%= @percentual_nota_na_media %>")
    const percentual_nota_ruim = parseFloat("<%= @percentual_nota_ruim %>")

    console.log("nota boa: ", percentual_boa_nota)

    var chart = new CanvasJS.Chart("chartContainer", {
      animationEnabled: true,
      title: {
        text: "Média de notas"
      },
      data: [{
        type: "pie",
        startAngle: 240,
        yValueFormatString: "##0.00\"%\"",
        indexLabel: "{label} {y}",
        dataPoints: [
          {y: percentual_boa_nota, label: "Boa nota"},
          {y: percentual_nota_na_media, label: "Nota Média"},
          {y: percentual_nota_ruim, label: "Nota ruim"}
        ]
      }]
    });
    chart.render();

    }
    </script>
    <div id="chartContainer" style="height: 370px; width: 100%;"></div>
    <script src="https://cdn.canvasjs.com/canvasjs.min.js"></script>

    <br>
</div>